image: docker:latest

stages:
  - build
  - test
  - production

variables:
  VERSION: '1.0'
  APP_IP: '172.16.111.186'

build_job:
  stage: build
  script:
    - docker build -t reddit:$VERSION reddit/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker tag reddit:$VERSION $CI_REGISTRY_USER/otus-reddit:$VERSION
    - docker push $CI_REGISTRY_USER/otus-reddit:$VERSION

test_job:
  stage: test
  script:
    - docker run --name test_unit -d $CI_REGISTRY_USER/otus-reddit:$VERSION
    - docker exec -i test_unit ruby -Creddit simpletest.rb
    - docker rm -f test_unit

production:
  stage: production
  image: ruby:2.4.2
  when: manual
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -o "StrictHostKeyChecking=no" sergey@$APP_IP "sudo docker rm -f reddit && sudo docker run --name reddit -d -p 9292:9292 $CI_REGISTRY_USER/otus-reddit:$VERSION"
  environment:
    name: production
    url: http://example.com
