version: '3'
services:

  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:5.6
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - back_net

  kibana:
    image: kibana:5.6
    ports:
      - "5601:5601"
    networks:
      - back_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
