---
- hosts: all
  become: true

  tasks:
    - name: Running the container
      docker_container:
        name: docker-reddit
        image: drcoyote/otus-reddit:1.0
        ports:
          - "9292:9292"
        state: started
